#+title: Problemas resueltos de la Olimpiada de Matemáticas en Hidalgo

Para contribuir con soluciones se sugieren los siguientes pasos:

- Obtener una cuenta gratuita en Github [[https://github.com/signup/free][aquí]], y enviarme un correo
  con el nombre de usuario para que lo incorpore a la lista de
  colaboradores. 

- Instalar el programa ~git~. Hay instrucciones [[http://help.github.com/set-up-git-redirect][aquí]].

- Obtener una "clave SSH", (lo cual necesitará crear una
  "passphrase", de preferencia, distinta a la contraseña de Github) y
  darla a Github, como se indica en la página del paso anterior.

- En nuestra máquina, usando la terminal, hay que dar el siguiente
  comando, el cual creará un subdirectorio llamado ~ProblemasOHM~, que
  contiene los archivos LaTeX que estamos editando.
  : $ git clone git@github.com:rvf0068/ProblemasOHM.git

- Editar algún archivo con cualquier editor.

- Con la terminal en el subdirectorio ~ProblemasOHM~, dar el comando 
  : $ git commit -am "Mensaje describiendo los cambios hechos"

- Nuevamente, con la terminal en el subdirectorio ~ProblemasOHM~, dar
  el comando (puede ser que el sistema nos pida la "passphrase"
  mencionada arriba)
  : $ git push

- Con el paso anterior, hemos subido nuestros cambios a
  Github. Podemos seguir editando los archivos y repitiendo los dos
  pasos anteriores cuantas veces sea necesario.

- Las siguientes ocasiones, antes de empezar a trabajar es buena idea
  bajar los cambios que hayan incorporado otros colaboradores, para
  lo cual es conveniente dar el comando (en el subdirectorio
  ~ProblemasOHM~).
  : $ git pull

Useful links:

- http://en.wikipedia.org/wiki/Git_(software)
- http://en.wikipedia.org/wiki/Github

